### ISSUE TITLE
Link to English Wiki in ReadMe cannot be found

### ISSUE THREAD

**Issue by PitaBreadGames** [yimengfan/BDFramework.Core#11]
![LinkToEnglishWikiNotFound](https://user-images.githubusercontent.com/22540356/61569908-5ad34400-aa3e-11e9-99ac-b97b1e77b9a7.PNG)

**Comment by yimengfan** [comment]
sorry ， My english is not will。so，The english wiki is not edit yet。

**Comment by PitaBreadGames** [comment]
Thank you for the reply! (:
