### ISSUE TITLE
资源热更 增量更新bug

### ISSUE THREAD

**Issue by qq1545372477** [yimengfan/BDFramework.Core#14]
A依赖B时 B改变 A不做任何变化时 打包出的AssetBundle两个资源也都会改变(AssetBundle包的md5有改变) 但现在的机制会跳过A 导致加载旧的A的AssetBundle包时 丢失对B的引用
测试环境 2019.1.11
A为Cube B为材质

**Comment by yimengfan** [comment]
你好，感谢你的反馈。
以下结果更新在Debuger分支中，
收到反馈后，我们第一时间进行了测试，但是很遗憾，经过检查，发现如下结果：
1.创建了cube 和材质mat01，颜色为红色，第一次进行打包，加载运行成功。无丢失
2.修改材质mat01为黑色，第二次打包，根据项目根目录下Android_changelist.json增量修改日志，和Art目录下的cache日志对比，发现 第二次也成功打出mat01的ab，并且hash命名也正确。
3.此时我检测配置，发现 cube这个引用配置也是指向新的mat hash也是正确的。
4.我们打印出 新ab中的所有资源名，发现指向的也是mat
总结：增量打包中，确实按照程序预设逻辑，检索出增量的文件，并且把增量文件进行打包处理。
ab打包后,也是成功导出，新的ab配置，也是指向新hash。
初步怀疑为unity bug，或者unity有新潜规则，不同批次的ab，无法自动进行依赖赋值。
另：如果你使用的是git版本控制，注意换行符格式问题，win和linux不同，会导致修改meta后，每次所有资源hash都是新的，可能会出现第二次增量，会多打出一部分。
因为hash规则，是使用prefab的.meta文件一起求hash，保证，prefab和。meta中值都不变时候，才会跳过。
如果您有相关的思路，和遇到相关问题，也请联系我们，感谢你对bdframe的支持，我们会尽快解决这个问题。。。

**Comment by yimengfan** [comment]
你好，bug已经修复。
主要原因是9月份优化版本hash命名导致的。
原因是，unity潜规则：building时设置的ab名，ab会利用这个进行依赖赋值。
所以第二次build出新的ab，则不能被正常依赖。
所以修改打包机制，ab名打包时则为路径名，生成后，修改为hash，则跟以前一样效果，只需编辑器略微修改。
