### ISSUE TITLE
README 勘误

### ISSUE THREAD

**Issue by yangruihan** [yimengfan/BDFramework.Core#18]
1. 
![image](https://user-images.githubusercontent.com/7806458/76810996-0087be80-682b-11ea-817a-4280720f822c.png)

**视屏 -> 视频**

2. 
![image](https://user-images.githubusercontent.com/7806458/76811017-0ed5da80-682b-11ea-837e-66c86601f761.png)

**Dpendent plugins -> Dependent plugins**

**Comment by yimengfan** [comment]
tks 收到
