### ISSUE TITLE
中后期项目可否使用BDFramework

### ISSUE THREAD

**Issue by Leovany** [yimengfan/BDFramework.Core#23]
刚接触到这个这框架，有种蠢蠢欲动想要使用的感觉，但目前项目进行到中后期阶段，如果要使用，方便修改吗？

**Comment by yimengfan** [comment]
得看原来的框架结构，如果大量的mono拖拽脚本，不太适合

**Comment by Leovany** [comment]
> 得看原来的框架结构，如果大量的mono拖拽脚本，不太适合

我看文档说【不允许任何脚本继承MonoBehavior.】，旧项目改动有点多，请问可以允许有少量挂预制体的Mono脚本存在吗？ 如果使用了，会怎么样？

**Comment by yimengfan** [comment]
ui组件 或者渲染相关组件是允许挂脚本的（业务逻辑相关的最好不要）， 不允许继承（主工程）是因为热更中跨域继承新手团队解决不好很多问题。
