### ISSUE TITLE
如何移植框架给其他项目使用（希望提供unitypackage包）

### ISSUE THREAD

**Issue by Leovany** [yimengfan/BDFramework.Core#25]
想导出 .unitypackage 给项目使用，但发现 BDFramework.Core 包含了Demo代码、UnitTest代码等，之间有互相依赖，导出.unitypackage 有错误。 请问下，哪些目录是需要导出的？

PS : 希望大大能提供下 unitypackage 包

**Comment by yimengfan** [comment]
![image](https://user-images.githubusercontent.com/26621257/82639245-f45d1a80-9c3a-11ea-96da-6e5054075423.png)
如果有命名空间报错，删除即可

**Comment by Leovany** [comment]
> ![image](https://user-images.githubusercontent.com/26621257/82639245-f45d1a80-9c3a-11ea-96da-6e5054075423.png)
> 如果有命名空间报错，删除即可

怎么图片显示不出来 =。=

**Comment by yimengfan** [comment]
翻墙

**Comment by Leovany** [comment]
> 翻墙

好了，谢谢~~
