### ISSUE TITLE
如何加载TP图集( 兼容 Resources.LoadAll 接口 )

### ISSUE THREAD

**Issue by Leovany** [yimengfan/BDFramework.Core#28]
官方文档写的是图集采用SA方案
但目前项目已经使用了TP方案，若修改SA方案估计有点难
替换旧接口【Resources.LoadAll】，比如
   ` Object[] allObj = Resources.LoadAll("Art/Cans/CansPack", typeof(UnityEngine.Sprite));`
却发现BResoureces 只有单个图片读取Load ....

请问下，该怎么兼容 Resources.LoadAll  接口？

**Comment by yimengfan** [comment]
考虑拓展接口，Assetbundle 和Assetdatabase 是否有loadall。（私以为tp方案维护管理很麻烦，平时操作零散的资源比较好，最终打包前，新建图集文件。

**Comment by Leovany** [comment]
> 考虑拓展接口，Assetbundle 和Assetdatabase 是否有loadall。（私以为tp方案维护管理很麻烦，平时操作零散的资源比较好，最终打包前，新建图集文件。

恩有的
1.  Assetdatabase 
    AssetDatabase.LoadAssetAtPath
2. Assetbundle 
    this.assetBundle.LoadAllAssets(type)
改动比较大，希望大大能补一下这个LoadAll 这个接口，我们全部项目都在用TP方案...
不甚感谢~~

**Comment by yimengfan** [comment]
已增加，但是assetbundle模式下有bug，只能应付简单的情况（只能保证图集没问题），不要大规模 各种复杂业务套用LoadALL接口。

![image](https://user-images.githubusercontent.com/26621257/82735383-f2d34580-9d53-11ea-934d-a89cfeea2de6.png)

![image](https://user-images.githubusercontent.com/26621257/82735375-dfc07580-9d53-11ea-841b-519d6b787ef5.png)

**Comment by Leovany** [comment]
> 已增加，但是assetbundle模式下有局限性，只能应付简单的情况（图集没问题），不要大规模 各种复杂业务套用LoadALL接口。
> 
> ![image](https://user-images.githubusercontent.com/26621257/82735383-f2d34580-9d53-11ea-934d-a89cfeea2de6.png)
> 
> ![image](https://user-images.githubusercontent.com/26621257/82735375-dfc07580-9d53-11ea-841b-519d6b787ef5.png)

谢谢大大的回复
我发现似乎漏了两处
1. 缺少AssetBundleMgr.LoadAssetBundle方法
   您的截图未贴出这个方法

2.  缺少 DevResourceMgr.LoadAll 方法
自己补充改写了下，将`Dictionary<string, UnityEngine.Object> objsMap` 改成数组结构 `Dictionary<string, UnityEngine.Object[]> objsMap` 
附代码如下：
` public T[] LoadAll<T>(string path) where T : UnityEngine.Object
        {
            if (objsMap.ContainsKey(path))
            {
                return objsMap[path] as T[];
            }
            else
            {
                var findTarget = "/Runtime/" + path + ".";
                var rets = this.allResourceList.FindAll((a) => a.Contains(findTarget));

                if (rets.Count == 0)
                {
                    Debug.LogError("未找到资源:" + path);
                }

                if (rets.Count > 1)
                {
                    foreach (var r in rets)
                    {
                        Debug.LogError("注意文件同名:" + r);
                    }
                }

                var resPath = rets[0];
                //objsMap[path] = AssetDatabase.LoadAllAssetsAtPath(resPath);

                List<T> list = new List<T>(objsMap[path].Length);
                foreach (Object o in objsMap[path])
                {
                    T t = o as T;
                    if (t != null)
                    {
                        // 强转成功 ( 存在 Null情况)
                        list.Add(t);
                    }
                }
                T[] objArray = list.ToArray();
                objsMap[path] = objArray;
                return objArray;
            }
        }`
