### ISSUE TITLE
继承AWindow 和  MonoBehaviour 的Window，是否可以共存混用 

### ISSUE THREAD

**Issue by Leovany** [yimengfan/BDFramework.Core#30]
因为旧项目原因，一次性改动太大，想分批改动Window界面
在想 AWindow 和  MonoBehaviour ，是否可以共存混用 
测试如下：
1.  Window_Login 继承AWindow
    TestMonoView : MonoBehaviour
2. 打AB包，上传到服务器
3. 逻辑如下，Login 界面 创建 MonoView 界面，然后在返回 MonoView `界面，点击返回，调用
`UIManager.Inst.ShowWindow(WinEnum.Win_Login);`  报错了，断点调试后发现 `UIManager.Inst` 竟然重新new对象了（ UIManager.Inst 在前面已经初始化，这是单例）

过来请教一下
1.  AWindow 和  MonoBehaviour ，是否可以共存混用 ？
    其他项目若要使用BD, 可能也会遇到这种情况，否则可能要一次性全部改完，累....
2. 为什么 UIManager.Inst 会new了两次？
   感觉像是两份独立空间？一个在BDFramework new , 另一个在Mono 这里new了一份，不是同一个？
3. 在代码 Editor 模式下，执行正常，但在 Persistent 就报这个错了
4. 在MonoBehaviour 可以在编辑器模式下断点调试，但BD 的代码不能断点调试？

谢谢~~

附图如下：
![5555](https://user-images.githubusercontent.com/2864116/83136343-df402a00-a119-11ea-9ae4-5dff6325ed82.png)

**Comment by Leovany** [comment]
测试另一种情况，AWindow 生成 Item对象 ( 继承MonoBehaviour )，发现了很奇怪的现象，allItem 集合有对象，在Editor下取出正常，而打包上传后，显示集合是有数量的，但取出allItem[0] 就为null 了？？？ 

![QQ图片20200529120805](https://user-images.githubusercontent.com/2864116/83220303-350de400-a1a5-11ea-9371-7ee6dfa4ecf2.png)

**Comment by yimengfan** [comment]
1，不能混用AWindows是逻辑对象，用来管理挂了MonoBehavior的Tranform还行
2.调试：
https://www.yuque.com/naipaopao/eg6gik/bgksew
3.热更相关：
![image](https://user-images.githubusercontent.com/26621257/83230866-1b789680-a1bd-11ea-9038-8b46076aa631.png)

![image](https://user-images.githubusercontent.com/26621257/83230715-d2c0dd80-a1bc-11ea-84ca-fc7f1cb0948c.png)
