### ISSUE TITLE
2019.4LTS在il2cpp模式真机运行报错

### ISSUE THREAD

**Issue by transong** [yimengfan/BDFramework.Core#32]
![image](https://user-images.githubusercontent.com/1109122/85222342-b5161b00-b3ec-11ea-9b52-2b7ba898bcc3.png)

mono模式下是好的

经查是Config的Awake在调用时Data还是空，可能是il2cpp初始化MonoBehaviour的问题

**Comment by yimengfan** [comment]
查询下 odin相关设置，这一块的序列化 都是用odin做的
