### ISSUE TITLE
ShaderCollection 收集不全

### ISSUE THREAD

**Issue by multiplatformsgamer** [yimengfan/BDFramework.Core#34]
ShaderCollection.cs 只收集的prefab.Material 的变体。没有收集Scene上的变体。而有些变体，比如URP 后期都是动态创建的材质。

**Comment by multiplatformsgamer** [comment]
而且prefab，material收集的时候只是单纯的静态资源上的变体，有些变体受到关照的影响，

**Comment by yimengfan** [comment]
文档里规范有说，动态修改的 需要新建材质丢到项目里以便搜集。
