### ISSUE TITLE
v2资源卸载问题

### ISSUE THREAD

**Issue by RookiePeter** [yimengfan/BDFramework.Core#36]
打包时会手动把自身依赖自己删除,卸载资源时只把依赖的计数减1,未减自身,导致自己卸载不掉

**Comment by yimengfan** [comment]
tks，后续会删除引用计数这一块。新版ab管理，其实没有必要卸载ab了，ab不实例化，占用只是个头文件消耗。 用户自己管理好自己实例化的卸载即可。
