### ISSUE TITLE
unity2019.3.14 一键收集Shader keyword无法收集keyword

### ISSUE THREAD

**Issue by duanma** [yimengfan/BDFramework.Core#38]
[test.zip](https://github.com/yimengfan/BDFramework.Core/files/6347662/test.zip)
![FA4$R${N1X9COW_YJC@(TM8](https://user-images.githubusercontent.com/13000981/115488328-e1a8f680-a28c-11eb-9706-b1ecc0d08b53.png)
如上图中的keyword在unity2019.3.14中无法收集到，且从相关shader中看到_ALPHABLEND_ON是位于local keywords下面，具体shader和材质见zip包

**Comment by yimengfan** [comment]
已解决
