### ISSUE TITLE
分模块打包功能需求

### ISSUE THREAD

**Issue by haozi000005** [yimengfan/BDFramework.Core#39]
希望可用在bdframework中增加分模块打包，分模块热更！！

**Comment by yimengfan** [comment]
好的，未来预计10月版本内加入

**Comment by yimengfan** [comment]
> @yimengfan 泡泡， 啥时候更新这个功能？

你把具体需求描述出来，因为2.0.8版本主要是重构ab管理编辑器这一块，如果来得及会在2.0.8 beta3版本中加入.

**Comment by haozi000005** [comment]
用户根据不同的内置模块选择性更新，类似于游戏商城，更新a游戏和更新b游戏不要求一起进行，可以单独更新b也可以单独更新a

**Comment by yimengfan** [comment]
> @yimengfan 用户根据不同的内置模块选择性更新，类似于游戏商城，更新a游戏和更新b游戏不要求一起进行，可以单独更新b也可以单独更新a

对于这个，代码动态切换dll会有很多遗留问题，比如对主工程的监听回调、开启的携程任务 、静态对象数据的污染，等需要手动清理，或者进行编码层的约束解决。
对于资源动态下载，目前已有的方式可以根据文件夹进行切分下载，2.0.8b4会新增一个模块tag功能，用户选择对应的tag进行下载，会下载对应模块tag资源和依赖资源部分。但是一样，对于各个模块的资源拆分 只能人为约束，不然各个模块公共资源很多 引用杂乱.
“对于代码 不建议分包，对于资源用tag标记分包，并且增加asset graph节点 和下载指定模块功能” 你看是否满足需求

**Comment by yimengfan** [comment]
你好，由于2.0.8b3版本原计划重构资源打包 加载模块 代码编写完后资源测试体量很大，对b4版本的分包加入有一定延期。预计2021.11月第一个礼拜完成大规模资源测试后，第二个礼拜才会进行b4版本的开发。届时会加入分包机制。如有影响研发，请多担待

**Comment by haozi000005** [comment]
先养好了在工作，身体第一

**Comment by yimengfan** [comment]
Fixed in 2.0.8 beta4.

**Comment by li10400** [comment]
已收到，谢谢！
