### ISSUE TITLE
LauncherBridge启动初始化的时候主工程里也包含了热更部分的type

### ISSUE THREAD

**Issue by AzellaK** [yimengfan/BDFramework.Core#45]
LauncherBridge启动初始化的时候主工程里也包含了热更部分的type
这个有其他方式获取主工程的type吗
![ZREDMA2IAB82H@FA7Q8ZT~J](https://user-images.githubusercontent.com/74393377/153665403-9aa2e364-369a-4e96-9af1-1c0a014f6a75.png)
![微信截图_20220212042213](https://user-images.githubusercontent.com/74393377/153665417-b4ccfc7a-33f1-4996-8f14-3c7a28cf15d1.png)
![6Y7DU3I{5 DK2O95M3_IK3R](https://user-images.githubusercontent.com/74393377/153665433-3414c4f6-c7a8-49a5-98af-673f40ca078d.png)

**Comment by yimengfan** [comment]
你好，这里设计上是有保留的（以防止被引擎裁切等），执行热更DLL代码时，若代码在DLL中有相同代码，会以执行热更DLL内的，不会出现跨域访问等情况。
未来会更新一个HotfixPipeline，可以自由控制热更代码在工程内，还是工程外。两种方案各有优略。
架构流程可以参考如下.
https://www.yuque.com/naipaopao/eg6gik/howuwq
