### ISSUE TITLE
更新的资源的依赖为空，会出现报空现象

### ISSUE THREAD

**Issue by azmja** [yimengfan/BDFramework.Core#49]
AssetbundleConfigLoder.GetDependAssetsByName<T>函数获取DependAssetIds时，DependAssetIds不为空，是"[]",其余的属性均有值,解决办法，判null然后 将retlist 手动赋值为0即可

**Comment by li10400** [comment]
已收到，谢谢！

**Comment by yimengfan** [comment]
Fixed in https://github.com/yimengfan/BDFramework.Core/commit/9581ca9905e45142527e38f8b62b2a4a22b25b73
