### ISSUE TITLE
Shader变体收集提示bug

### ISSUE THREAD

**Issue by csdjk** [yimengfan/BDFramework.Core#63]
如果没有runtime目录（paths空数组），AssetDatabase.FindAssets("t:Shader", paths) 会返回所有shader啊，然后全部都提示“不建议将shader放在runtime中,没有mat信息 无法搜集变体！”

**Comment by li10400** [comment]
已收到，谢谢！

**Comment by yimengfan** [comment]
你好，在BD的资源系统里是必须有“Runtime”目录的，如果想在其他环境用，修改为自己项目的资源路径就好了

**Comment by csdjk** [comment]
好的，谢谢
