### ISSUE TITLE
2.3版本无法通过upm安装

### ISSUE THREAD

**Issue by yangzijianGit** [yimengfan/BDFramework.Core#66]
https://openupm.cn/packages/com.code-philosophy.hybridclr/?subPage=versions

hybridclr 的版本中没有2.4.3，无法安装

**Comment by li10400** [comment]
已收到，谢谢！

**Comment by yimengfan** [comment]
收到，会在近期升级到upm5

**Comment by yimengfan** [comment]
收到，会在近期升级到hylcr 5.0，之前3.0以下才支持2019

**Comment by yimengfan** [comment]
收到，会在近期升级到hylcr 5.0，之前3.0以下才支持2019，你可以手动修改更高的版本号。

**Comment by yimengfan** [comment]
已经在2.4.0中修复，hyclr升级到 5.0.0
