### ISSUE TITLE
upm 2.4 版本 unity 2021 报错

### ISSUE THREAD

**Issue by yangzijianGit** [yimengfan/BDFramework.Core#67]
![image](https://github.com/yimengfan/BDFramework.Core/assets/46264835/acf0a022-bc33-4b7f-b2a5-187689d7681e)
![image](https://github.com/yimengfan/BDFramework.Core/assets/46264835/acd82fd8-d400-4a29-bfe1-b653503d14f6)

**Comment by yimengfan** [comment]
你好暂时并未适配2021，该分支主要为2019工程工作
